# Generated by Django 4.2.19 on 2025-02-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('rejected', 'Rejected'), ('eval_pending', 'Awaiting Evaluation'), ('approved', 'Approved for Listing')], default='pending', max_length=20),
        ),
    ]
