# Generated by Django 4.2.19 on 2025-03-03 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_price_alter_property_assigned_contractor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.AlterField(
            model_name='property',
            name='assigned_contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.contractor'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('rejected', 'Rejected'), ('eval_pending', 'Awaiting Evaluation'), ('approved', 'Approved for Listing')], default='pending', max_length=20),
        ),
    ]
