# Generated by Django 4.2.19 on 2025-03-05 17:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_completion_date_property_completion_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='work_areas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kitchen', 'مطبخ'), ('bathroom', 'حمام'), ('bedroom', 'غرفة نوم'), ('living_room', 'غرفة معيشة'), ('full_house', 'المنزل بالكامل'), ('exterior', 'خارجي'), ('roof', 'سقف'), ('plumbing', 'سباكة'), ('electrical', 'كهرباء'), ('other', 'أخرى')], help_text='حدد جميع المناطق التي تحتاج إلى عمل', max_length=100, verbose_name='مناطق العمل'),
        ),
        migrations.AddField(
            model_name='property',
            name='work_details',
            field=models.TextField(blank=True, help_text='قدم وصفاً مفصلاً للعمل المطلوب لكل منطقة', null=True, verbose_name='تفاصيل العمل'),
        ),
    ]
